final project
Tadessejemal1/Budget-App pull request #13
Opened 2022-12-22 15:53 UTC by Tadessejemal1

final

2022-12-22 17:16 UTC, DeliceLydia requested changes
## Hi @Tadessejemal1, 

Good job so far! There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!




### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-22 17:16 UTC, DeliceLydia commented on app/views/categories/index.html.erb
> +  </div>
- [ ] Please follow the given design on the buttons it has to look like this
<img width="547" alt="Screen Shot 2022-12-22 at 19 06 03" src="https://user-images.githubusercontent.com/44745855/209188629-b2fe50ec-1810-417d-9d51-aba474b6cc41.png">
its not
<img width="109" alt="Screen Shot 2022-12-22 at 19 08 49" src="https://user-images.githubusercontent.com/44745855/209189021-1ad9dd1b-4f8f-44cf-b30e-5cca23363016.png">

2022-12-22 17:16 UTC, DeliceLydia commented on app/views/categories/index.html.erb
> +  </div>
- [ ] Please use the same `colors`, `typography`, `layouts`

2022-12-22 17:16 UTC, DeliceLydia commented on README.md
> +
- [ ] Please give credit to  [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2022-12-22 20:18 UTC, Tadessejemal1 commented on README.md
> +
![image](https://user-images.githubusercontent.com/85793292/209219003-bf90debe-c047-440f-962d-fbc88a8f416b.png)

2022-12-22 20:19 UTC, Tadessejemal1 commented on README.md
> +
Thank you for the feedback I can fix the styles on the button

2022-12-22 21:10 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @Tadessejemal1 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

- [ **OPTIONAL** ] I think it would be better if for your next projects where you are required to use Gitflow to open your pull request from feature to dev. It is good to merge a **PR** in a dev branch after it has been reviewed. For a short reminder about **[gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)**, I suggest you read this **[article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)** 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 21:10 UTC, tresorsawasawa commented on README.md
> +  Original design idea by Gregoire Vella on Behance
- [ **OPTIONAL** ] Good job adding the credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) as mentioned the previous reviewer. But, I think it would be better if you hyperlink his name so any can user can easily check out the design template if hee wants. I suggest you update it to some thing like this or similar:
```
- Thanks to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=)
```

2022-12-22 21:10 UTC, tresorsawasawa commented on app/views/categories/index.html.erb
> +  </div>
- [ ] As mentioned by the previous reviewer to use the correct  `colors`, `typography`, `layouts`,... like the one used on the template design. I think you should improve the **Add Category** button design by using the correct `background color,` `paddings`, `removing the underline text decoration`,...

| Template design | Your design |
| --------------------- | ------------------ |
| ![Screenshot_template](https://user-images.githubusercontent.com/44745855/209188629-b2fe50ec-1810-417d-9d51-aba474b6cc41.png) | ![Screenshot from 2022-12-22 22-58-06](https://user-images.githubusercontent.com/83042742/209224838-cdd638c6-f869-447d-83b5-317da9ab5661.png) |

Here are the colors used in the template:
![Screenshot from 2022-12-22 23-01-28](https://user-images.githubusercontent.com/83042742/209225347-f3556322-5524-4740-b3de-a5d12e6c2e6a.png)

2022-12-23 09:06 UTC, Tadessejemal1 commented on app/views/categories/index.html.erb
> +  </div>
Thank you for the feedback. I can fix styles to meet the template design.
I have done styles as much as possible similar to the original design by fixing background color, and paddings, and removing the underline text decoration.
Template design
![image](https://user-images.githubusercontent.com/85793292/209306407-d5385ebf-c8d8-4a6a-b7f6-82d593d2b1db.png)

my work 
![image](https://user-images.githubusercontent.com/85793292/209306599-f2b4ee69-f7f2-4c5d-a5bd-f63ec74a775c.png)

2022-12-23 09:07 UTC, Tadessejemal1 commented
I have done styles as much as possible similar to the original design by fixing background color, and paddings, and removing the underline text decoration.
Template design
![image](https://user-images.githubusercontent.com/85793292/209306407-d5385ebf-c8d8-4a6a-b7f6-82d593d2b1db.png)

my work 
![image](https://user-images.githubusercontent.com/85793292/209306599-f2b4ee69-f7f2-4c5d-a5bd-f63ec74a775c.png)

2022-12-23 10:06 UTC, KDlamini approved these changes
### Hi @Tadessejemal1 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ App follows the design guidelines
✔️ Author of the original design is acknowledged

# Status: Approved ✔️ 

![simon](https://user-images.githubusercontent.com/38088818/209315881-92326ea4-1d06-4cf0-bfef-ded805d0986c.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 13:57 UTC, merged